list_of_cols_1 = [
                [0, "ID_zakazky", 1, ""],
                [1, "ID_casti_zakazky", 0, ""],
                [2, "Systemove_cislo_zakazky", 0, ""],
                [3, "Evidencni_cislo_zakazky", 0, ""],
                [4, "cislo_vysledku_zadavaciho_rizeni", 0, ""],
                [5, "Interni_cisla_smluvobjednavek", 0, ""],
                [6, "Nazev_zakazky", 1, ""],
                [7, "Nazev_casti_zakazky", 0, ""],
                [8, "Externi_zastoupeni_zadavatele_v_rizeni", 0, ""],
                [9, "Externi_zastoupeni_zadavatele_v_rizeni_nazev", 0, ""],
                [10, "Externi_zastoupeni_zadavatele_v_rizeni_IcO", 0, ""],
                [11, "Druh_verejne_zakazky", 1, ""],
                [12, "Druh_zadavaciho_rizeni", 1, ""],
                [13, "Typ_zakazky", 1, ""],
                [14, "Varianta_druhu_rizeni", 1, ""],
                [15, "Jedna_se_o_cast_VZ", 1, ""],
                [16, "Zakazka_zavadejici_DNS", 0, ""],
                [17, "Faze_zakazky", 1, ""],
                [18, "Celkova_predpokladana_hodnota_zakazky_bez_DPH_Kc", 1, "money"],
                [19, "Zakazka_souvisejici_s_vykonem_relevantni_cinnosti", 0, ""],
                [20, "Hlavni_NIPEZ_kod_zakazky", 0, ""],
                [21, "Organizacni_jednotka_spravy", 1, ""],
                [22, "Datum_zahajeni_zadavaciho_rizeni", 1, ""],
                [23, "Lhuta_pro_podani_nabidek_na_profilu", 0, ""],
                [24, "Datum_otevirani_nabidek_na_profilu", 0, ""],
                [25, "Lhuta_pro_doruceni_zadosti_o_ucast_na_profilu", 0, ""],
                [26, "Hodnotici_kriteria", 0, ""],
                [27, "Vysledkem_je_ramcova_dohoda", 1, ""],
                [28, "Hodnoceni_formou_elektronicke_aukce_prostrednictvim_TA", 0, ""],
                [29, "Hodnoceni_formou_elektronicke_aukce_mimo_aplikaci_TA", 0, ""],
                [30, "Spolecnosti_oslovene_k_podani_nabidky_pocet", 1, ""],
                [31, "Spolecnosti_oslovene_k_podani_nabidky_nazev", 0, ""],
                [32, "Pocet_zadosti_o_ucast", 0, ""],
                [33, "Seznam_zadosti_o_ucast", 0, ""],
                [34, "Pocet_nabidek", 1, ""],
                [35, "Seznam_nabidek_a_nabidkova_cena_bez_DPH", 0, ""],
                [36, "ucastnik_zadavaciho_rizeni_nazev", 0, ""],
                [37, "Nazev_smluvniho_partnera", 1, ""],
                [38, "IcO_smluvniho_partnera", 0, ""],
                [39, "Smluvni_cena_bez_DPH_Kc", 1, "money"],
                [40, "Smluvni_cena_s_DPH_Kc", 1, "money"],
                [41, "Datum_uzavreni_smlouvy", 1, "date"],
                [42, "Skutecne_uhrazena_cena_bez_DPH", 0, ""],
                [43, "Skutecne_uhrazena_cena_s_DPH", 0, ""]
               ]

list_of_cols2 = [
                [1, "ID_v_databazi", 0, ""],
                [2, "ID_zakazky", 0, ""],
                [3, "Interni_cislo_zakazky", 0, ""],
                [4, "Systemove_cislo_zakazky", 0, ""],
                [5, "Evidencni_cislo_zakazky", 0, ""],
                [6, "Datum_vytvoreni_zakazky", 0, "date"],
                [7, "Organizacni_jednotka_spravy", 0, ""],
                [8, "Nazev_zakazky", 0, ""],
                [9, "Strucny_popis", 0, ""],
                [10, "Hlavni_NIPEZ_kód_zakazky", 0, ""],
                [11, "Druh_verejne_zakazky", 0, ""],
                [12, "Typ_zakazky", 0, ""],
                [13, "Druh_zadavaciho_rizeni", 0, ""],
                [14, "Varianta_druhu_rizeni", 0, ""],
                [15, "Faze_zakazky", 0, ""],
                [16, "Datum_uverejneni_predbeznych_informaci", 0, ""],
                [17, "Datum_zahajeni_zadavaciho_rizeni", 0, ""],
                [18, "Lhuta_pro_podani_nabidek_na_profilu", 0, ""],
                [19, "Lhuta_pro_doruceni_zadosti_o_ucast_na_profilu", 0, ""],
                [20, "Datum_otevirani_nabidek_na_profilu", 0, ""],
                [21, "Prijimani_nabidek_elektronicky_v_systemu_TA", 0, ""],
                [22, "Zpusob_hodnoceni", 0, ""],
                [23, "Vysledkem_je_ramcova_dohoda", 0, ""],
                [24, "Kontaktni_osoba_Jmeno_a_prijmeni", 0, ""],
                [25, "Kontaktni_osoba_e-mail", 0, ""],
                [26, "Zastupujici_osoba_Jmeno_a_prijmeni", 0, ""],
                [27, "Zastupujici_osoba_e-mail", 0, ""],
                [28, "Celkova_predpokladana_hodnota_zakazky_bez_DPH_Kc", 0, ""],
                [29, "Celkova_predpokladana_hodnota_zakazky_s_DPH_Kc", 0, ""],
                [30, "Mena", 0, ""],
                [31, "Datum_uzavreni_smlouvy", 0, ""],
                [32, "Interni_cisla_smluv_objednavek", 0, ""],
                [33, "IcO_smluvniho_partnera", 0, ""],
                [34, "Nazev_smluvniho_partnera", 0, ""],
                [35, "Datum_zacatku_platnosti", 0, ""],
                [36, "Datum_konce_platnosti", 0, ""],
                [37, "Smlouva_na_dobu_neurcitou", 0, ""],
                [38, "Smluvni_cena_bez_DPH_Kc", 0, "money"],
                [39, "Smluvni_cena_s_DPH_Kc", 0, "money"],
                [40, "cislo_vysledku_zadavaciho_rizeni", 0, ""],
                [41, "Skutecne_uhrazena_cena_bez_DPH", 0, ""],
                [42, "Skutecne_uhrazena_cena_s_DPH", 0, ""],
                [43, "Datum_zruseni_zakazky", 0, ""],
                [44, "Duvod_zruseni_zakazky", 0, ""],
                [45, "Zakladajici_uzivatel", 0, ""],
                [46, "Zakladajici_jednotka", 0, ""]
]

airbnb_listings = [
                    [1, "room_id", 1, ""],
                    [2, "name", 1, ""],
                    [3, "propertytype", 1, ""],
                    [4, "roomtype", 1, ""],
                    [5, "bathrooms", 1, ""],
                    [6, "bedrooms", 1, ""],
                    [7, "capacity", 1, ""],
                    [8, "cleaningfee", 1, ""],
                    [9, "latitude", 1, ""],
                    [10, "longitude", 1, ""],
                    [11, "minnights", 1, ""],
                    [12, "picturecount", 1, ""],
                    [13, "overall_rating", 1, ""],
                    [14, "user_id", 1, ""],
                    [15, "user_name", 1, ""],
                    [16, "user_superhost", 1, ""],
                    [17, "reviews_total", 1, ""],
                    [18, "room_created", 1, ""],
                    [19, "room_lastupdate", 1, ""]
]

airbnb_occupancy = [
                    [1, "room_id", 1, ""],
                    [2, "yearmon", 1, ""],
                    [3, "days_occupied", 1, ""],
                    [4, "occupancy_rate", 1, ""],
                    [5, "mean_price", 1, ""],
                    [6, "reviews_count", 1, ""]
]

granty_mhmp = [
                    [1, "rok_evidence", 0, ""],
                    [2, "cislo_projektu", 0, ""],
                    [3, "nazev_projektu", 0, "str"],
                    [4, "popis", 0, "str"],
                    [5, "stav", 0, "str"],
                    [6, "nazev_programu", 0, "str"],
                    [7, "typ_dotace", 0, "str"],
                    [8, "nazev_oblasti", 0, "str"],
                    [9, "ucel_dotace", 0, "str"],
                    [10, "rok_od", 0, ""],
                    [11, "rok_do", 0, ""],
                    [12, "castka_naklady", 0, ""],
                    [13, "castka_pozadovana", 0, ""],
                    [14, "castka_pridelena", 0, ""],
                    [15, "castka_vycerpana", 0, ""],
                    [16, "id_projekt", 0, ""],
                    [17, "id_zadatel", 0, ""]
]
zadatele_mhmp = [
                    [1, "rok_evidence", 0, ""],
                    [2, "nazev", 0, "str"],
                    [3, "ic", 0, ""],
                    [4, "pravni_forma", 0, "str"],
                    [5, "ulice", 0, "str"],
                    [6, "cislo_popisne", 0, ""],
                    [7, "cislo_orientacni", 0, ""],
                    [8, "mestska_cast", 0, "str"],
                    [9, "psc", 0, ""],
                    [10, "obec", 0, "str"],
                    [11, "id_projekt", 0, ""],
                    [12, "id_zadatel", 0, ""]
]

cpv_codes = [
                    [1, 'cpv_code', 0, 'str'],
                    [2, 'cpv_name', 0, 'str'],
                    [3, 'cpv_id', 0, ''],
                    [4, 'parent_cpv', 0, '']
]
